smas:
    - name: "RuleA"
      market: "BTC-USDT"
      fieldName1: "openingPrice"
      fieldName2: "closingPrice"
      timeInterval1: 1
      timeInterval2: 1
      alarmCondition: "lower"

    - name: "RuleC"
      market: "BTC-USDT"
      fieldName1: "openingPrice"
      fieldName2: "closingPrice"
      timeInterval1: 1
      timeInterval2: 1
      alarmCondition: "greater"

